### ISSUE TITLE
Fullscreen not working in iOS

### ISSUE THREAD

**Issue by anishg-cn** [liqvidjs/liqvid#28]
I have included this, <script src="https://unpkg.com/@liqvid/host/lv-host.js"></script>, in the index.html `<head>` tag, but still when I click Fullscreen icon in the player in iOS it is not making the player Fullscreen. It just toggles the icon.

Please help.

package information:
"liqvid": "^2.1.5",
"liqvid-scripts": "0.0.5",

**Comment by anishg-cn** [comment]
@ysulyma can you please check this?

**Comment by anishg-cn** [comment]
@ysulyma iOS version is 10. The player is not in iframe it is in the webpage and i have not used iframe anywhere in the application so the lv-host script is included in the index.html of the application.

**Comment by ysulyma** [comment]
Including the player directly into a webpage is not yet supported (I am researching this for Liqvid 2.2). The recommended way to use Liqvid is to include your video in an `<iframe>` (as you would do with a YouTube video—this is so that your video can be safely displayed on other sites). If your video needs to integrate with code in the parent webpage, you can do so with [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage).
