### ISSUE TITLE
Video element issue

### ISSUE THREAD

**Issue by anishg-cn** [liqvidjs/liqvid#31]
When adding a Video element which has duration less than the total duration of the playback, then the playback is pausing when the video ends. @ysulyma Can you please check?

You can reproduce the issue by the following steps:

1. Go to https://liqvidjs.org/docs/reference/Video.
2. Change the line 7 in the code segement from `["train/", "0:20"]` to `["train/", "0:30"]`
3. Then run the video, you will see that at 23s, when the video ends the player will pause automatically.

**Comment by ysulyma** [comment]
This is a known issue, I'll have a go at fixing it

**Comment by anishg-cn** [comment]
@ysulyma can you tell me what is the issue? and how long will it take to fix?

**Comment by ysulyma** [comment]
@anishg-cn We render `<Audio>` and `<Video>` elements without controls, so generally they're synced up with Liqvid playback, and can only be played/paused via the `<Player>` controls. There's one exception: the underlying `<audio>`/`<video>` elements can be affected by play/pause keyboard buttons. To support this case, we pause the `Playback` when the `<video>` gets paused. The bug is that we're treating the end of the video as a pause of the video. I can probably get this done in the next day or two!

**Comment by anishg-cn** [comment]
@ysulyma ok thanks

**Comment by ysulyma** [comment]
@anishg-cn try with Liqvid 2.1.8!

**Comment by anishg-cn** [comment]
@ysulyma yes this is working now, thanks.
